feat: test output color
fredrikaverpil/neotest-golang pull request #208
Opened 2024-10-25 15:32 UTC by jaymorelli96

Hi @fredrikaverpil  this is what I came up with. I have also updated the documentation. This option is false by default.

I would like to add a screenshot of how it looks but it seems that I don't have access to the assets folder?

Also, I haven't included tests for this, not sure if it is expected for this?

Please let me know if it follows the conventions and it is idiomatic, as I said I don't have experience with Lua and plugin development. The changes are very small, so not sure if I can get much feedback from it 😄 

Example of how it looks:
![image](https://github.com/user-attachments/assets/f0b03ccb-4e81-46d6-b006-e28677b158ec)

2024-10-25 19:16 UTC, fredrikaverpil requested changes
Hey @jaymorelli96 thank you for this, it looks and works really nice!
I especially like how the colors match up with the color scheme in use.

I also actually think we can make this the default, so I have given some suggestions on changes. 😄 

Can you also just please add this into the options.lua:

https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/options.lua

And into these tests for the options:

https://github.com/fredrikaverpil/neotest-golang/blob/e64292c12ab95c37ec21eaf33e21e8c5d56c8d29/tests/unit/options_spec.lua

2024-10-25 19:16 UTC, fredrikaverpil commented on README.md
> +| `colorize_test_output`        | `false`                           | Enable output color for `SUCCESS`, `FAIL`, and `SKIP` tests. See [here](https://github.com/fredrikaverpil/neotest-golang#output-c
Please set the default value to `true` and remove the link.

```suggestion
| `colorize_test_output`   | `true`                            | Enable output color for `SUCCESS`, `FAIL`, and `SKIP` tests.                                                                                                                                                                                                                                                                         |
```

2024-10-25 19:16 UTC, fredrikaverpil commented on README.md
> +
The README is already rather big and I also feel people will understand what this feature will do without a code example. I think we can just skip this. Ok?

```suggestion
```

2024-10-28 14:25 UTC, jaymorelli96 commented
Cool,  thanks @fredrikaverpil! Can you please take a look at the new changes?

2024-10-28 17:01 UTC, fredrikaverpil approved these changes
Very nice!  
Thank you! 🎉 😄

2024-10-28 17:01 UTC, merged