feat: using DAP without nvim-dap-go
fredrikaverpil/neotest-golang pull request #216
Opened 2024-11-09 18:05 UTC by HeavyPunk

Hello! I have a nvim config that contains a many of DAP configurations for some languages, also for golang. I don't want to install additional plugin special for debugging go apps or tests (this breaks a consistency of my config). I setup own DAP configuration for this and wanna use it to debug tests with your plugin.

2024-11-09 19:12 UTC, fredrikaverpil commented
Hey @HeavyPunk and many thanks for your contribution!

I think this is great and I actually have a colleague at work who wants to not to depend on sap-go as well.

I'm a little busy at the moment but let me take the time to review properly and then let's definitively allow manual DAP config. 👍

2024-11-09 19:54 UTC, HeavyPunk commented
Great! Also I give you example how this feature used in my config:
``` lua
require("neotest-golang") {
          dap_manual_enabled = true,
          dap_manual_configuration = {
            name = "Debug go tests",
            type = "go", -- preconfigured DAP adapter name
            request = "launch",
            mode = "test",
          }
        }
```

2024-11-19 20:56 UTC, HeavyPunk commented
Hey @fredrikaverpil ! I fixed a strategy selector to prevent loading dap-go and manual-dap modules before executing a logic. At now all of them are lazy-loaded.
This also fixed all tests

2024-11-21 16:25 UTC, fredrikaverpil requested changes
Great work @HeavyPunk!

I had some minor comments. I can implement these changes myself and get this merged if you like.

2024-11-21 16:25 UTC, fredrikaverpil commented on lua/neotest-golang/features/dap/dap_manual.lua
> +local dap = require("dap")
Unused, looks like it can be removed.

2024-11-21 16:25 UTC, fredrikaverpil commented on lua/neotest-golang/features/dap/dap_manual.lua
> +  logger.debug("Nothing to check. Manual DAP configuration in use")
Let's make this a no-op instead, no need to even log something here unless we can detect a problem.

2024-11-22 14:53 UTC, HeavyPunk commented
Thank you for your review, @fredrikaverpil ! I implement your suggestions by myself. I call you here a bit later after fixing of code

2024-11-22 14:59 UTC, HeavyPunk commented on README.md
> +- DAP support for your own DAP configuration.
Hi!🖐 Yes, my example is enough for configuring DAP (only `type` field required additional info because it is user-specific parameter). I think this feature will be used by users who know how to configure DAP

2024-11-22 15:04 UTC, HeavyPunk commented on tests/unit/options_spec.lua
> +      dap_manual_enabled = false,
I think this is good idea. It will be more scaleable

2024-12-01 16:14 UTC, HeavyPunk commented
Hey @fredrikaverpil ! It's ready for your review 😀

2024-12-03 15:08 UTC, fredrikaverpil commented
Many thanks @HeavyPunk, I'll have a look and make any additional touch-ups to e.g. README but then I'll merge it in. Looks great, overall!

2024-12-03 20:49 UTC, HeavyPunk commented
Thanks! I will be waiting for merge :tada:

2024-12-04 18:03 UTC, fredrikaverpil approved these changes
🚀 super nice, thank you @HeavyPunk

2024-12-04 18:03 UTC, merged